01-Class-Content/25-Power-Packs/Django/Lesson-3/Activities/11-Form-Helpers/Unsolved/app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

app_name = 'users'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('users.urls')),
]

01-Class-Content/25-Power-Packs/Django/Lesson-3/Activities/11-Form-Helpers/Unsolved/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^index/$', views.UserListView.as_view(), name='index'),

    url(r'^detail/(?P<pk>[0-9]+)/$', 
        views.UserDetailView.as_view(), name='detail'),

    url(r'^add/$', views.add, name='add'),
]

01-Class-Content/25-Power-Packs/Django/Lesson-3/Activities/11-Form-Helpers/Unsolved/users/models.py
from django.db import models

from django.utils import timezone

# Create your models here.
class User(models.Model):

    created = models.DateTimeField(default=timezone.now())

    modified = models.DateTimeField(default=timezone.now())
    
    first_name = models.CharField(max_length=256, blank=False, null=False)

    last_name = models.CharField(max_length=256, blank=False, null=False)

    email = models.CharField(max_length=256, blank=False, null=False)

    age = models.IntegerField(blank=True, null=True)

    def __str__(self):
        """ Sensible string representation of a user."""
        return "{0} {1} | {2}".format(self.first_name, self.last_name, 
                self.email)

    def save(self, *args, **kwargs):
        """ Add created_at and updated_at timestamps. """
        if not self.id:
            self.created = timezone.now()

        self.modified = timezone.now()

        return super(User, self).save(*args, **kwargs)

01-Class-Content/25-Power-Packs/Django/Lesson-3/Activities/11-Form-Helpers/Unsolved/users/views.py
from django.http import Http404, HttpResponse

from django.shortcuts import redirect, render

from django.views.generic import DetailView, ListView

from .models import User

class UserListView(ListView):
    model = User
    template_name = 'users/index.html'

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)

        # In real life we'd retrieve this from the session.
        context['name'] = 'Adonis'
        
        return context

class UserDetailView(DetailView):
    model = User
    template_name = 'users/detail.html'

def add(request):

    if request.method == 'POST':
        # First, assert all keys are present. This is already tedious--
        #   imagine how bad it gets when we want granular information
        #   on missing submissions.

        complete = True
        missing = None

        for key in ['first-name', 'last-name', 'email', 'age']:
            if not request.POST[key]:
                complete = False
                missing = key

        if not complete:
            return render(request, 'users/add.html', 
                    { 'error' : 'Error: Please include data for {0}'.format(missing) })

        else:
            # Create and save directly.

            User(
             first_name=request.POST['first-name'], 
             last_name=request.POST['last-name'],
             email=request.POST['email'],
             age=request.POST['age']).save()
        
        return redirect('users:index')

    else:
        return render(request, 'users/add.html', { 'header' : 'GET' })

01-Class-Content/25-Power-Packs/Django/Lesson-3/Activities/11-Form-Helpers/Unsolved/users/templates/users/add.html
{% extends 'users/base.html' %}

{% block title %} Add {% endblock %}

{% block content %}

  {% if header %}
  
    <h1>{{ header }}</h1>

  {% elif error %}

    <h1>{{ error }}</h1>

  {% endif %}

    <hr>

    <form method="post" action="{% url 'users:add' %}">

      {% csrf_token %}

      <div class="form-group">
        <label for="first-name">First Name</label>
        <input class="form-control" type="text" name="first-name" placeholder="First Name" required>
      </div>

      <div class="form-group">
        <label for="last-name">Last Name</label>
        <input class="form-control" type="text" name="last-name" placeholder="Last Name" required>
      </div>

      <div class="form-group">
        <label for="email">Email</label>
        <input class="form-control" type="text" name="email" placeholder="Email" required>
      </div>

      <div class="form-group">
        <label for="age">Age</label>
        <input class="form-control" type="number" name="age" required>
      </div>

      <button type="submit" class="btn btn-primary">Submit</button>

    </form>

{% endblock %}

01-Class-Content/25-Power-Packs/Django/Lesson-3/Activities/11-Form-Helpers/Unsolved/users/templates/users/base.html
<!DOCTYPE html>
<html>
  <head>
  
    <meta charset="utf-8">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap CSS, no JS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  </head>
  <body>

    <div class="container">
      {% block content %} {% endblock %}
    </div>

  </body>
</html>

01-Class-Content/25-Power-Packs/Django/Lesson-3/Activities/11-Form-Helpers/Unsolved/users/templates/users/detail.html
{% extends 'users/base.html' %}

{% block title %} Detail {% endblock %}

{% block content %}

<h1>Welcome, {{ user.first_name }}.</h1>

  <hr>

<h5 >Profile Information</h5>

<table class="table table-striped table-bordered">
  <tr>
    <td>First Name</td>
    <td>{{ user.first_name }}</td>
  </tr>

  <tr>
    <td>Last Name</td>
    <td>{{ user.last_name }}</td>
  </tr>

  <tr>
    <td>Email</td>
    <td>{{ user.email }}</td>
  </tr>

</table>

{% endblock %}

01-Class-Content/25-Power-Packs/Django/Lesson-3/Activities/11-Form-Helpers/Unsolved/users/templates/users/index.html
{% extends 'users/base.html' %}

{% block title %} Index {% endblock %}

{% block content %}

  {% if name %}
    <h1>Hello, {{ name }}!</h1>
  {% else %}
    <h1>Hello, Stranger!</h1>
  {% endif %}

  {% if user_list %}
    <ul class="list-group">
    {% for user in user_list %} 
      <li class="list-group-item">{{ user }}</li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No users yet.</p>
  {% endif%}

{% endblock %}